name: Build Pybind11 Extension

on:
  push:
    paths:
      - "src/**"
      - "include/**"
      - "CMakeLists.txt"
      - ".github/workflows/build-pybind.yml"

jobs:
  build-linux-so:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build .so inside Ubuntu 20.04 container
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app ubuntu:20.04 /bin/bash -c "
            apt update &&
            DEBIAN_FRONTEND=noninteractive apt install -y cmake g++ python3 python3-dev python3-pip git &&
            pip3 install pybind11 &&
            mkdir -p build &&
            cd build &&
            cmake .. &&
            make &&
            so_file=\$(find ../python -name 'strategy_py*.so' | head -n 1) &&
            cp \$so_file ../python/strategy_py.so
          "

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit compiled .so
        run: |
          git add python/strategy_py.so
          git commit -m "Add compiled Linux .so file" || echo "No changes to commit"

      - name: Pull latest changes
        run: |
          git pull origin main --rebase || echo "Skipping pull due to local changes"

      - name: Push back to repo
        run: git push origin main
