name: Build Pybind11 Extension

on:
  push:
    paths:
      - "src/**"
      - "include/**"
      - "CMakeLists.txt"
      - ".github/workflows/build-pybind.yml"

jobs:
  build-linux-so:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pybind11 and build tools
        run: |
          sudo apt update
          sudo apt install -y cmake g++ python3-dev
          pip install pybind11

      - name: Build Pybind11 shared object
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Rename compiled .so file in-place
        run: |
          so_file=$(find python -name 'strategy_py*.so' | head -n 1)
          mv "$so_file" python/strategy_py.so

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Pull latest changes
        run: |
          git pull origin main --rebase

      - name: Commit compiled .so
        run: |
          git add python/strategy_py*.so
          git commit -m "Add compiled Linux .so file" || echo "No changes to commit"

      - name: Push back to repo
        run: git push origin main
