name: Build Pybind11 Extension

on:
  push:
    paths:
      - "src/**"
      - "include/**"
      - "CMakeLists.txt"
      - ".github/workflows/build-pybind.yml"

jobs:
  build-linux-so:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pybind11 and build tools
        run: |
          sudo apt update
          sudo apt install -y cmake g++ python3-dev
          pip install pybind11

      - name: Build Pybind11 shared object
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Move .so to python directory
        run: |
          find build -name '*.so' -exec cp {} python/strategy_py.so \;

      - name: Commit built .so file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add python/strategy_py.so
          git commit -m "Auto-build pybind11 .so file for deployment" || echo "No changes"
          git push
